---
# Debian install
- name: (Debian) install wpa-supplicant on Debian
  apt:
    name: '{{ wpasupplicant__pkg_name_d }}={{ wpasupplicant__version_d }}'
    state: present
    update_cache: '{{ wpasupplicant__pkg_update_cache }}'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Redhat install
- name: (Redhat) Install on Redhat
  block:
    - name: Install epel-release
      yum:
        name:
          - epel-release
        state: latest
        update_cache: '{{ wpasupplicant__pkg_update_cache }}'

    - name: Install wpa_supplicant
      yum:
        name: '{{ wpasupplicant__pkg_name_c }}'
        state: latest
        update_cache: '{{ wpasupplicant__pkg_update_cache }}'
  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        msg: 'I caught an error'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
...
