---
# hostapd service
hostapd__state: started
hostapd__enabled: True
hostapd__version_d: '2:2.7+git20190128+0c1e29f-6+deb10u2'

hostapd__pkg_update_cache: '{{ pkg_update_cache | default("true") }}'

# defaults file for hostapd
# look at https://w1.fi/cgit/hostap/plain/hostapd/hostapd.conf
hostapd__configs:
  - name: all_available_values
    hostapd__acct_server_addr: '{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}'
    hostapd__acct_server_port: 1813
    hostapd__acct_server_shared_secret: 'anHardSharedSecret'
    hostapd__auth_algs: 3
    hostapd__auth_server_addr: '{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}'
    hostapd__auth_server_port: 1812
    hostapd__auth_server_shared_secret: 'anHardSharedSecret'
    hostapd__channel: 1
    hostapd__ctrl_interface: '/var/run/hostapd'
    hostapd__ctrl_interface_group: 0
    hostapd__driver: 'nl80211'
    hostapd__dynamic_vlan: 0                # values are 0, 1 and 2
    hostapd__eap_reauth_period: 3600
    hostapd__eap_server: 0
    hostapd__hw_mode: 'g'
    hostapd__ieee8021x: 1
    hostapd__interface: 'wlan0'
    hostapd__logger_syslog: 1
    hostapd__macaddr_acl: 0
    hostapd__max_num_sta: 255
    hostapd__nas_identifier: 'ap.example.com'
    hostapd__own_ip_addr: '{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}'
    hostapd__radius_das_port: 3799
    hostapd__radius_das_client: '192.168.1.123 shared secret here'
    hostapd__radius_das_time_window: 300
    hostapd__radius_das_require_event_timestamp: 1
    hostapd__radius_das_require_message_authenticator: 1
    hostapd__ssid: 'default_ssid'
    hostapd__vlan_file_content: ''          # linked with hostapd__dynamic_vlan and hostapd__vlan_file
    hostapd__vlan_file: ''                  # linked with hostapd__dynamic_vlan 
    hostapd__wpa: 2
    hostapd__wpa_key_mgmt: 'WPA-PSK WPA-EAP'
    hostapd__wpa_pairwise: 'TKIP CCMP'
    hostapd__wpa_passphrase: 'secret passphrase'
    hostapd__wpa_psk: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
