---
# hostapd deploy configurations
- name: Deploy Configs for hostapd
  template:
    src: hostapd.conf.j2
    dest: '/etc/hostapd/hostapd_{{ item.name }}.conf'
    backup: yes

- name: Add vlan_file for hostapd
  template:
    src: hostapd.vlan.j2
    dest: '{{ item.hostapd__vlan_file }}'
    backup: yes
  when: item.hostapd__vlan_file is defined

