---
# hostapd deploy configurations
- name: Deploy Configs for hostapd
  template:
    src: hostapd.conf.j2
    dest: '/etc/hostapd/hostapd_{{ item.name }}.conf'
    backup: yes

- name: Add Default Config for hostapd
  copy:
    src: hostapd_default.conf
    dest: '/etc/hostapd/hostapd.conf'
    backup: yes
